language: android

android:
  components:
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository
    - extra-android-support

before_install:
  - yes | sdkmanager "platforms;android-29"

script:
  - ./gradlew assembleDebug