language: android

android:
  components:
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository
    - extra-android-support

before_install:
  - yes | sdkmanager "platforms;android-25"

script:
  - ./gradlew assembleDebug